# Generated by Django 3.1.6 on 2021-02-02 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, verbose_name='Unique identifier for traceability')),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for validation and processing'), ('PAYMENT_OK', 'Payment accepted'), ('BEING_COOKED', 'Kitchen working on it'), ('COOKED', 'Ready to be delivered'), ('DELIVERY', 'Delivery in progress'), ('DELIVERED', 'Delivered')], default='NEW', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
