# Generated by Django 3.1.6 on 2021-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard menu'), ('XXL', 'XXL Menu')], max_length=40, verbose_name='Selected menu'),
        ),
    ]
