# Generated by Django 3.1.6 on 2021-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_card_number',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_cvc',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for validation and processing'), ('PAYMENT_OK', 'Payment accepted'), ('PAYMENT_CANCELLED', 'Payment cancelled'), ('PAYMENT_FAILED', 'Payment failed'), ('KITCHEN_SCHEDULED', 'Scheduled to be cooked'), ('KITCHEN_CANCELLED', 'Cancelling cooking'), ('KITCHEN_FAILED', 'Kitchen failure'), ('DELIVERY_SCHEDULED', 'Scheduled to be deliveed'), ('DELIVERY_CANCELLED', 'Cancelling delivery'), ('DELIVERY_FAILED', 'Delivery failure'), ('BEING_COOKED', 'Kitchen working on it'), ('COOKED', 'Ready to be delivered'), ('DELIVERY', 'Delivery in progress'), ('DELIVERED', 'Delivered')], default='NEW', max_length=20, verbose_name='Status'),
        ),
    ]
