# Generated by Django 3.1.6 on 2021-10-11 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersagatracker',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Unique identifier for traceability'),
        ),
    ]
