# Generated by Django 3.1.6 on 2021-02-03 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, verbose_name='Unique identifier for traceability')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Delivery in progress'), ('DELIVERED', 'Successfully delivered'), ('FAILED', "Could'n t deliver")], default='NEW', max_length=20, verbose_name='Status')),
                ('departure_time', models.DateTimeField(verbose_name='Estimated or real time of departure')),
                ('arrival_time', models.DateTimeField(verbose_name='Estimated or real time of arrival')),
            ],
        ),
    ]
