# Generated by Django 3.1.6 on 2021-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(verbose_name='Unique identifier for traceability')),
                ('menu', models.CharField(blank=True, choices=[('STANDARD', 'Standard menu'), ('XXL', 'XXL Menu')], max_length=40, verbose_name='Selected menu')),
                ('preparation_start', models.DateTimeField(null=True, verbose_name='Preparation: start date/time')),
                ('preparation_end', models.DateTimeField(null=True, verbose_name='Preparation: end date/time')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled to be cooked'), ('IN_PROGRESS', 'Being cooked'), ('COOKED', 'Cooked - ready to be picked'), ('PICKED', 'Picked by delivery service')], default='NEW', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
