# Generated by Django 3.1.6 on 2022-01-10 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuorder',
            name='preparation_estimated_end',
            field=models.DateTimeField(null=True, verbose_name='Preparation: estimated start'),
        ),
        migrations.AddField(
            model_name='menuorder',
            name='preparation_estimated_start',
            field=models.DateTimeField(null=True, verbose_name='Preparation: estimated start'),
        ),
    ]
